[package]

name = "pistoncore-glutin_window"
version = "0.0.9"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["glutin", "window", "piston"]
description = "A Piston window back-end using the Glutin library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/glutin_window.git"
homepage = "https://github.com/pistondevelopers/glutin_window"

[lib]

name = "glutin_window"
path = "src/lib.rs"

# [dependencies.pistoncore-input]
# git = "https://github.com/PistonDevelopers/input"

# [dependencies.pistoncore-window]
# git = "https://github.com/PistonDevelopers/window"

# [dependencies.glutin]
# git = "https://github.com/tomaka/glutin"

# [dependencies.gl]
# git = "https://github.com/bjz/gl-rs"

# [dependencies.shader_version]
# git = "https://github.com/PistonDevelopers/shader_version"

[dependencies]
gl = "0.0.12"
glutin = "0.1.6"
pistoncore-input = "0.0.9"
pistoncore-window = "0.1.2"
shader_version = "0.0.6"

