[package]

name = "pistoncore-glutin_window"
version = "0.0.4"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["glutin", "window", "piston"]
description = "A Piston window back-end using the Glutin library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/glutin_window.git"
homepage = "https://github.com/pistondevelopers/glutin_window"

[lib]

name = "glutin_window"
path = "src/lib.rs"

[dependencies.pistoncore-window]
git = "https://github.com/PistonDevelopers/window"
#version = "0.0.1"

[dependencies.pistoncore-input]
git = "https://github.com/PistonDevelopers/input"
#version = "0.0.1"

[dependencies.quack]
git = "https://github.com/PistonDevelopers/quack"

[dependencies.shader_version]
git = "https://github.com/PistonDevelopers/shader_version"
#version = "0.0.0"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
#version = "0.0.0"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
#version = "0.0.2"
